### ISSUE TITLE
version for armhf arch?

### ISSUE THREAD

**Issue by Havivw** [nccgroup/scrying#35]

**Comment by sciguy16** [comment]
Are you able to compile it from source on armhf? I haven't been able to do any testing on ARM yet, and cross-compiling from x86_64 requires cross-compiling a bunch of -sys libraries separately. Unfortunately Github Actions doesn't provide ARM-based runners (https://github.com/actions/virtual-environments/issues/2536) so any builds will have to be done via qemu or an external runner.

I can have a go at building it on a raspberry pi, but can't give any timescales for when I'll have time to do that.

The OpenSSL sub-dependency helpfully provides a `vendored` feature to build it as part of the cargo build process, but the other -sys subdependencies will need building manually
```toml
[target.arm-unknown-linux-gnueabihf.dependencies]
openssl-sys = { version = "0.9", features = ["vendored"] }
```
